image: niccokunzmann/ci-latex

PDFs:
  stage: build
  script:
  - pdflatex -interaction=nonstopmode -halt-on-error My-Questionnaire.tex
  - cd GodSpeed
  - pdflatex -interaction=nonstopmode -halt-on-error GodSpeed.tex
  - cd ../RoSAS
  - pdflatex -interaction=nonstopmode -halt-on-error RoSAS.tex
  only:
  - master
  artifacts:
    paths:
    - My-Questionnaire.pdf
    - GodSpeed/GodSpeed.pdf
    - RoSAS/RoSAS.pdf    